apiVersion: batch/v1
kind: CronJob
metadata:
  name: training
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: training
            image: bash
            command: ["bash", "-c", "echo Current date is $(date)"]
          restartPolicy: OnFailure
