apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeployment
  labels:
    service: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    service: web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: web
  type: LoadBalancer
