apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  volumes:
  - name: data
    emptyDir: {}
  containers:
  - name: datagen
    image: debian
    command: ["/bin/sh","-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 10;
        done
    volumeMounts:
    - name: data
      mountPath: /html
  - name: datadis
    image: nginx
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
